/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: db09f9715ee8cf257e62230d89276df9)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env {
		AI: Ai;
		OPENROUTER_BASE_URL: string;
		OPENROUTER_MODEL: string;
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
	}
}
interface Env extends Cloudflare.Env {
	OPENROUTER_API_KEY?: string;
	WORKERS_AI_MODEL?: string;
}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENROUTER_BASE_URL" | "OPENROUTER_MODEL">> {}
}
